ruby_rails/RailsDeviseApp/config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'
  
  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'
  
  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'
  
  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'
  
  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'

  resources :board_messages
  resources :board_users
  resources :data_pages
  get 'hello/index'
  get 'hello/login_check'
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

ruby_rails/RailsDeviseApp/app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message:'は、必須項目です。'}
end

ruby_rails/RailsDeviseApp/app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :set_board_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  layout 'board_messages'

  # GET /board_messages
  # GET /board_messages.json
  def index
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    users = BoardUser.where('account_id == ?', current_account.id)[0]
    if users == nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where('account_id == ?', current_account.id)[0]
    end
    @board_user = users
    @board_message = BoardMessage.new
    @board_message.board_user_id = @board_user.id
  end

  # GET /board_messages/1
  # GET /board_messages/1.json
  def show
    redirect_to '/board_messages'
  end

  # GET /board_messages/new
  def new
    redirect_to '/board_messages'
  end

  # GET /board_messages/1/edit
  def edit
    redirect_to '/board_messages'
  end

  # POST /board_messages
  # POST /board_messages.json
  def create
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    @board_message = BoardMessage.new(board_message_params)
    @board_user = BoardUser.where('account_id == ?', current_account)[0]
    respond_to do |format|
      if @board_message.save
        format.html { redirect_to '/board_messages' }
        format.json { render :show, status: :created, location: @board_message }
      else
        format.html { render :index }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_messages/1
  # PATCH/PUT /board_messages/1.json
  def update
    redirect_to '/board_messages'
  end

  # DELETE /board_messages/1
  # DELETE /board_messages/1.json
  def destroy
    redirect_to '/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_message
      @board_message = BoardMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_message_params
      params.require(:board_message).permit(:content, :board_user_id)
    end
end

ruby_rails/RailsDeviseApp/app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

ruby_rails/RailsDeviseApp/app/views/board_messages/_form.html.erb
<%= form_with(model: board_message, local: true) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_message.errors.count, "error") %> prohibited this board_message from being saved:</h2>

      <ul>
        <% board_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :board_user_id %>
    <div class="border p-1"><%= @board_user.nickname %></div>
    <%= form.hidden_field :board_user_id %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ruby_rails/RailsDeviseApp/app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

ruby_rails/RailsDeviseApp/app/views/board_messages/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="display-4 text-primary">Message Board</h1>
<%= render 'form', board_message: @board_message %>
<p><%= link_to 'go home >>', controller: :board_users %></p>
<hr>

<h2 class="h4">※Posted Messages.</h2>
<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th width="200px">User</th>
    </tr>
  </thead>

  <tbody>
    <% @board_messages.each do |board_message| %>
      <tr>
        <td><%= board_message.content %></td>
        <td><%= link_to board_message.board_user.nickname, 
            controller: :board_users, action: :show, 
            id:board_message.board_user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><%= paginate @board_messages %></div>
<hr>
<div>copyright SYODA-Tuyano 2020</div>

ruby_rails/RailsDeviseApp/app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

ruby_rails/RailsDeviseApp/app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>